# Generated by Django 4.0.5 on 2022-06-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del administrador')),
                ('cargoAdministrador', models.CharField(default='null', max_length=80, verbose_name='Cargo del administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Id de la categoria')),
                ('nombreCategoria', models.CharField(default='null', max_length=100, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la Comuna')),
                ('nombreComuna', models.CharField(max_length=80, verbose_name='Nombre de la Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la provincia')),
                ('nombreProvincia', models.CharField(max_length=80, verbose_name='Nombre de la provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la region')),
                ('nombreRegion', models.CharField(max_length=80, verbose_name='Nombre de la region')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('nombreUsuario', models.CharField(max_length=80, verbose_name='Nombre del usuario')),
                ('correoUsuario', models.CharField(max_length=80, unique=True, verbose_name='Correo del usuario')),
                ('passUsuario', models.CharField(max_length=80, verbose_name='Password del usuario')),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.comuna')),
                ('Provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.provincia')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.region')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.region'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precioProducto', models.IntegerField(verbose_name='precio del producto')),
                ('descripcionProducto', models.CharField(max_length=900, verbose_name='Descripcion del producto')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idCompra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la compra')),
                ('cantidadProductos', models.IntegerField(verbose_name='Cantidad de productos')),
                ('totalCompra', models.IntegerField(verbose_name='Total de la compra')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del empleado')),
                ('rolEmpleado', models.CharField(default='null', max_length=80, verbose_name='Rol del empleado')),
                ('Administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.administrador')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='Provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.usuario'),
        ),
    ]
